# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zns < Formula
  desc "A CLI tool for querying DNS records with readable, colored output."
  homepage "https://github.com/znscli/zns"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_darwin_amd64.tar.gz"
      sha256 "d6ba2f6bfd2f98b52847ac8a109419e6d1b87e1bbc400848b6b5f9e19acd0a56"

      def install
        bin.install "zns"
      end
    end
    on_arm do
      url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_darwin_arm64.tar.gz"
      sha256 "445236a302f3ecb6d00e1d76c40a403f4e72ac04fbf001cb8d3dd9d271abdf9d"

      def install
        bin.install "zns"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_linux_amd64.tar.gz"
        sha256 "be0d2a09992e098e333f4f32ce449ad2b95030afce1ee887dd033990b726f2d9"

        def install
          bin.install "zns"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_linux_arm64.tar.gz"
        sha256 "5bc3046e9db110530f94c25e9f7dc47bb46e925edc552fd30a6b9a959c871403"

        def install
          bin.install "zns"
        end
      end
    end
  end

  test do
    system "#{bin}/zns -v"
  end
end
