# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zns < Formula
  desc "A CLI tool for querying DNS records with readable, colored output."
  homepage "https://github.com/znscli/zns"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_darwin_amd64.tar.gz"
      sha256 "7681251761de3c709c8e38b3dcfdccb75a9a853d68d82009c69c7b9fe5a8f920"

      def install
        bin.install "zns"
      end
    end
    on_arm do
      url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_darwin_arm64.tar.gz"
      sha256 "7472063c1e40618533c5be006b7fbff33025952b0ff6f956a65b2151eb45696b"

      def install
        bin.install "zns"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_linux_amd64.tar.gz"
        sha256 "71421cef2d732d731c25d2eb077df1ebe87e5f8c706c1e8fa2a545791aa6056d"

        def install
          bin.install "zns"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/znscli/zns/releases/download/v0.2.0/zns_0.2.0_linux_arm64.tar.gz"
        sha256 "f2b4fbcebe82e2ea1ad1d6d0bdb89a7981b2481677ca9a22e3688c3b2bdea35c"

        def install
          bin.install "zns"
        end
      end
    end
  end

  test do
    system "#{bin}/zns -v"
  end
end
